service: get-secrets-with-lambda-extension

plugins: 
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs16.x
  stage: test
  region: eu-north-1
  environment: ${file(env.yml):test}
  iam:
    role:
      statements: 
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - 'arn:aws:secretsmanager:eu-north-1:{your-account-id}:secret:{your-secret-name}'

functions:
  displaySecrets:
    handler: src/displaySecrets/handler.displaySecrets
    layers:
      - 'arn:aws:lambda:eu-north-1:427196147048:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2'
    memorySize: 128
    timeout: 5

package:
  individually: true